Repository wyruweso/sqlglot-js, pull requests merged in 2023-06, with the labels that each got.

#1 - Refactoring
  .editorconfig
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierrc.js
  package-lock.json
  package.json
  src/common/dataStructure/trie/trie.ts
  src/common/dataStructure/trie/types/trieLookupStatus.ts
  src/index.ts
  src/tokenizer/config/dialect/defaultTokenizerGrammar.ts
  src/tokenizer/config/tokenizerGrammar.ts
  src/tokenizer/config/types/commentConfig.ts
  src/tokenizer/config/types/keywordConfig.ts
  src/tokenizer/config/types/singleTokenConfig.ts
  src/tokenizer/config/types/varSingleTokenConfig.ts
  src/tokenizer/config/types/whitespaceConfig.ts
  src/tokenizer/dto/token.ts
  src/tokenizer/enums/tokenType.ts
  src/tokenizer/tokenizer.ts
  tsconfig.json
Labels: bug, enhancement

#2 Added backlog file
  BACKLOG.MD
Labels: enhancement

#3 Fix linter issues. Fixed missing argument in trie constructor
  .eslintrc.json
  .prettierrc.cjs
  package-lock.json
  package.json
  src/common/dataStructure/trie/trie.ts
  src/common/dataStructure/trie/types/trieLookupStatus.ts
  src/index.ts
  src/tokenizer/config/dialect/defaultTokenizerGrammar.ts
  src/tokenizer/config/tokenizerGrammar.ts
  src/tokenizer/config/types/commentConfig.ts
  src/tokenizer/config/types/keywordConfig.ts
  src/tokenizer/config/types/singleTokenConfig.ts
  src/tokenizer/config/types/varSingleTokenConfig.ts
  src/tokenizer/config/types/whitespaceConfig.ts
  src/tokenizer/dto/token.ts
  src/tokenizer/enums/tokenType.ts
  src/tokenizer/tokenizer.ts
Labels: bug

#4 Feature/add tests
  .gitignore
  .mocharc.json
  package-lock.json
  package.json
  src/tokenizer/tokenizer.ts
  tests/tokenizer/tokenizer.spec.ts
Labels: enhancement
